version: '3'
services:
  talent_probe:
    build: .
    volumes:
      - ./profiles:/app/profiles
      - ./error_logs/app:/app/error_logs/api_errors
      - ./error_logs/app:/app/error_logs/app_errors
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
    command: sh
